/*
   MoreBasicFunctions - A LibreOffice Add-On written in Java that provides more basic functions.
   Copyright (C) 2021 Julien Férard.

   MoreBasicFunctions is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   MoreBasicFunctions is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/
#ifndef INCLUDED_COM_GITHUB_JFERARD_MBFS_XTESTS
#define INCLUDED_COM_GITHUB_JFERARD_MBFS_XTESTS

#include <com/sun/star/uno/XInterface.idl>
#include <com/sun/star/uno/RuntimeException.idl>

module com { module github { module jferard { module mbfs {

interface XTests {
    /**
    Assert that two objects are equal
    */
    void assertEquals([in] string msg, [in] any o1, [in] any o2);

    /**
    Assert that two arrays are equal
    */
    void assertArrayEquals([in] string msg, [in] sequence<any> o1, [in] sequence<any> o2);

    /**
    Assert that two objects are not equal
    */
    void assertNotEquals([in] string msg, [in] any o1, [in] any o2);

    /**
    Assert that two arrays are not equal
    */
    void assertArrayNotEquals([in] string msg, [in] sequence<any> o1, [in] sequence<any> o2);

    /**
    Assert that a condition is true
    */
    void assertTrue([in] string msg, [in] boolean b);

    /**
    Assert that a condition is false
    */
    void assertFalse([in] string msg, [in] boolean b);

    /**
    Finalize the tests
    */
    long errors();

    /**
    Return the message
    */
    string message();

    /**
    Raise an error if some tests failed
    */
    void check() raises (com::sun::star::uno::RuntimeException);
};

}; }; }; };

#endif

