/*
   MoreBasicFunctions - A LibreOffice Add-On written in Java that provides more basic functions.
   Copyright (C) 2021 Julien Férard.

   MoreBasicFunctions is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   MoreBasicFunctions is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/
#ifndef INCLUDED_COM_GITHUB_JFERARD_MBFS_XUTILS
#define INCLUDED_COM_GITHUB_JFERARD_MBFS_XUTILS

#include <com/sun/star/uno/XInterface.idl>
#include <com/sun/star/beans/PropertyValue.idl>

module com { module github { module jferard { module mbfs {

interface XUtils: ::com::sun::star::uno::XInterface {
    /*
    Return true if the string matches the extglob pattern (man 1 bash)
    */
    boolean glob([in] string str, [in] string pattern);

    /*
    Return a PropertyValue
    */
    ::com::sun::star::beans::PropertyValue makePV([in] string name, [in] any value);

    /*
    Return an array of PropertyValues
    */
    sequence<::com::sun::star::beans::PropertyValue> makePVs([in] sequence<any> namesAndValues);

    /*
    Return a byte from a string
    */
    byte parseByte([in] string number);

    /*
    Return a double from a string
    */
    double parseDouble([in] string number);

    /*
    Return a float from a string
    */
    float parseFloat([in] string number);

    /*
    Return a hyper (= long) from a string
    Does *not* work.
    */
    hyper parseHyper([in] string number);

    /*
    Return a long (= int) from a string
    */
    long parseLong([in] string number);

    /*
    Return a short from a string
    */
    short parseShort([in] string number);

};

}; }; }; };

#endif
