/*
   MoreBasicFunctions - A LibreOffice Add-On written in Java that provides more basic functions.
   Copyright (C) 2021 Julien Férard.

   MoreBasicFunctions is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   MoreBasicFunctions is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/
#ifndef INCLUDED_COM_GITHUB_JFERARD_MBFS_XMBFSSET
#define INCLUDED_COM_GITHUB_JFERARD_MBFS_XMBFSSET

#include <com/sun/star/uno/XInterface.idl>
#include <com/sun/star/beans/IllegalTypeException.idl>
#include <com/sun/star/container/XIndexReplace.idl>
#include <com/sun/star/container/XEnumerationAccess.idl>
#include <com/sun/star/container/NoSuchElementException.idl>
#include <com/sun/star/lang/IndexOutOfBoundsException.idl>
#include <com/sun/star/lang/IllegalArgumentException.idl>
#include <com/sun/star/lang/WrappedTargetException.idl>
#include <com/sun/star/lang/WrappedTargetException.idl>
#include <com/sun/star/container/XSet.idl>

module com { module github { module jferard { module mbfs {

/**
A hash set.

Basic: use  `EnumerableMap` with value = key
*/
interface XMBFSSet {
    /**
    Implements `XSet`
    */
    interface ::com::sun::star::container::XSet;

    /**
    Return the size of this set
    */
    long size();

    /**
    Take an element from the set and return it.
    */
    any take()
            raises ( ::com::sun::star::container::NoSuchElementException);

    /**
    Insert a collection of elements in the set.
    */
    void insertCollection([in] any collection)
            raises( ::com::sun::star::lang::IllegalArgumentException,
                    ::com::sun::star::lang::IndexOutOfBoundsException,
                    ::com::sun::star::lang::WrappedTargetException,
                    ::com::sun::star::container::NoSuchElementException
                    );

    /**
    Return an array with the elements of the set. The size of the array is the exact size of the
    set.
    */
    sequence<any> toArray();
};

}; }; }; };

#endif
